#pragma once

// --------------------------------------- \\
//      Sdk Generated By ( CheatGear )     \\
// --------------------------------------- \\
// Name: ARK_Survival_Evolved, Version: Patch_346.14

#include <set>
#include <string>
#include <vector>
#include <locale>
#include <unordered_set>
#include <unordered_map>
#include <iostream>
#include <sstream>
#include <cstdint>
#include <Windows.h>

#include "SDK/BasicTypes_Package.h"
#include "SDK/CoreUObject_Package.h"
#include "SDK/InputCore_Package.h"
#include "SDK/SlateCore_Package.h"
#include "SDK/Engine_Package.h"
#include "SDK/AIModule_Package.h"
#include "SDK/Slate_Package.h"
#include "SDK/MovieSceneCore_Package.h"
#include "SDK/UMG_Package.h"
#include "SDK/OnlineSubsystem_Package.h"
#include "SDK/OnlineSubsystemUtils_Package.h"
#include "SDK/ShooterGame_Package.h"
#include "SDK/WorldModifiersContainer_BP_Package.h"
#include "SDK/DataListEntryWidgetGeneric_AutomaticRefresh_Package.h"
#include "SDK/DataListButton_ListSession_Package.h"
#include "SDK/EngineMessages_Package.h"
#include "SDK/ListSessions_Package.h"
#include "SDK/VivoxCore_Package.h"
#include "SDK/UdpMessaging_Package.h"
#include "SDK/OptionsMenu_Package.h"
#include "SDK/ScriptPlugin_Package.h"
#include "SDK/Telemetry_Package.h"
#include "SDK/MainMenuGameMode_Package.h"
#include "SDK/DataListButton_MainMenu_Package.h"
#include "SDK/DataListButton_HostSession_Package.h"
#include "SDK/UI_HelpPage_Package.h"
#include "SDK/ProceduralSettings_Package.h"
#include "SDK/FPVMeleeHitCameraShakeMobile_Package.h"
#include "SDK/RagdollKinematicActor_BP_Package.h"
#include "SDK/StartScreenUI_Package.h"
#include "SDK/SessionMessages_Package.h"
#include "SDK/CustomMeshComponent_Package.h"
#include "SDK/OculusLibrary_Package.h"
#include "SDK/FPVMeleeHitCameraShake_Package.h"
#include "SDK/ToolTipWidgetMiniHelp_Package.h"
#include "SDK/MainMenu_Package.h"
#include "SDK/GameLiveStreaming_Package.h"
#include "SDK/TrueSkyPlugin_Package.h"
#include "SDK/CreditsUI_Package.h"
#include "SDK/MovieSceneCoreTypes_Package.h"
#include "SDK/MainMenuUI_Package.h"
#include "SDK/SponsoredModsUI_Package.h"
#include "SDK/HostSession_Package.h"
#include "SDK/OnlineSubsystemSteam_Package.h"
#include "SDK/OnlineSubsystemEOS_Package.h"
#include "SDK/ToolTipWidgetPrimalItem_Inventory_Package.h"
#include "SDK/GamepadButtonLegend_Package.h"
#include "SDK/DmgTypeBP_Environmental_Package.h"
#include "SDK/PrimalGlobalsBlueprint_Package.h"
#include "SDK/MoviePlayer_Package.h"
#include "SDK/ConfirmationDialogGeneric_Package.h"
#include "SDK/EngineSettings_Package.h"
#include "SDK/MediaAssets_Package.h"
